algorithm: uulearn_ulb_ulb
save_dir: ./saved_models/ulb_ulb/classic_cv/uulearn_ulb_ulb
save_name: uulearn_ulb_ulb_fmnist_target3_neg7_ulb1_30000_0.4_ulb2_30000_0.6_42
resume: True
load_path: ./saved_models/ulb_ulb/classic_cv/uulearn_ulb_ulb/uulearn_ulb_ulb_fmnist_target3_neg7_ulb1_30000_0.4_ulb2_30000_0.6_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_train_iter: 50000
num_eval_iter: 500
num_log_iter: 10
batch_size: 64
eval_batch_size: 128
epoch: 50
crop_ratio: 1.0
img_size: 28
data_dir: ./data
dataset: fmnist
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.0005
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
net: lenet5
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: None
target_classes: [5, 7, 9]
neg_classes: None
num_ulb1_data: 30000
num_ulb2_data: 30000
cls_prior_ulb1: 0.4
cls_prior_ulb2: 0.6
