algorithm: uulearn_ulb_ulb
save_dir: ./saved_models/ulb_ulb/classic_cv/uulearn_ulb_ulb
save_name: uulearn_ulb_ulb_stl10_target4_neg6_ulb1_5000_0.8_ulb2_5000_0.2_42
resume: True
load_path: ./saved_models/ulb_ulb/classic_cv/uulearn_ulb_ulb/uulearn_ulb_ulb_stl10_target4_neg6_ulb1_5000_0.8_ulb2_5000_0.2_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_train_iter: 50000
num_eval_iter: 500
num_log_iter: 10
batch_size: 32
eval_batch_size: 128
epoch: 50
crop_ratio: 0.875
img_size: 96
data_dir: ./data
dataset: stl10
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
net: resnet18
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10025
dist_backend: nccl
gpu: None
target_classes: [0, 1, 8, 9]
neg_classes: None
num_ulb1_data: 5000
num_ulb2_data: 5000
cls_prior_ulb1: 0.8
cls_prior_ulb2: 0.2
