algorithm: confdiff_abs_conf_diff
save_dir: ./saved_models/conf_diff/classic_cv/confdiff_abs_conf_diff
save_name: confdiff_abs_conf_diff_cifar100_target40_neg60_pair25000_prior0.4_custom_resnet18_42
resume: True
load_path: ./saved_models/conf_diff/classic_cv/confdiff_abs_conf_diff/confdiff_abs_conf_diff_cifar100_target40_neg60_pair25000_prior0.4_custom_resnet18_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_train_iter: None
num_eval_iter: None
num_log_iter: 50
batch_size: 64
eval_batch_size: 128
epoch: 50
crop_ratio: 0.875
img_size: 32
data_dir: ./data
dataset: cifar100
num_classes: 100
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
net: resnet18
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10063
dist_backend: nccl
gpu: 0
activation: abs
target_classes: [4, 30, 55, 72, 95, 1, 32, 67, 73, 91, 3, 42, 43, 88, 97, 15, 19, 21, 31, 38, 34, 63, 64, 66, 75, 26, 45, 77, 79, 99, 27, 29, 44, 78, 93, 36, 50, 65, 74, 80]
neg_classes: None
num_pair_data: 25000
class_prior: 0.4
conf_model_name: custom_resnet18
