algorithm: risksd_sim_dsim_ulb
save_dir: ./saved_models/sim_dsim_ulb/classic_cv/risksd_sim_dsim_ulb
save_name: risksd_sim_dsim_ulb_fmnist_target5_neg5_sim_dsim_pair5000_ulb20000_prior0.7_42
resume: True
load_path: ./saved_models/sim_dsim_ulb/classic_cv/risksd_sim_dsim_ulb/risksd_sim_dsim_ulb_fmnist_target5_neg5_sim_dsim_pair5000_ulb20000_prior0.7_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_train_iter: 30000
num_eval_iter: None
num_log_iter: 25
batch_size: 32
eval_batch_size: 128
epoch: 30
crop_ratio: 1.0
img_size: 28
data_dir: ./data
dataset: fmnist
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.0005
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
net: lenet5
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10010
dist_backend: nccl
gpu: None
uratio: 1
target_classes: [0, 1, 2, 3, 4]
neg_classes: None
num_pair_data: 5000
num_ulb_data: 20000
class_prior: 0.7
lb_data: sim_dsim
