algorithm: upu_pos_ulb
save_dir: ./saved_models/pos_ulb/classic_cv/upu_pos_ulb
save_name: upu_pos_ulb_mnist_target5_neg5_pos100_ulbNone_42
resume: True
load_path: ./saved_models/pos_ulb/classic_cv/upu_pos_ulb/upu_pos_ulb_mnist_target5_neg5_pos100_ulbNone_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_train_iter: 50000
num_eval_iter: None
num_log_iter: 50
batch_size: 64
eval_batch_size: 128
epoch: 50
crop_ratio: 1.0
img_size: 28
data_dir: ./data
dataset: mnist
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.0005
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
net: lenet5
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10003
dist_backend: nccl
gpu: None
include_lb_to_ulb: False
uratio: 1
target_classes: [0, 1, 2, 3, 4]
neg_classes: None
num_pos_data: 100
num_ulb_data: None
