algorithm: var_pu_pos_ulb
save_dir: ./saved_models/pos_ulb/classic_cv/var_pu_pos_ulb
save_name: var_pu_pos_ulb_stl10_target4_neg6_pos500_ulbNone_42
resume: True
load_path: ./saved_models/pos_ulb/classic_cv/var_pu_pos_ulb/var_pu_pos_ulb_stl10_target4_neg6_pos500_ulbNone_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_train_iter: 100000
num_eval_iter: None
num_log_iter: 50
batch_size: 32
eval_batch_size: 128
epoch: 50
crop_ratio: 0.875
img_size: 96
data_dir: ./data
dataset: stl10
num_classes: 10
num_workers: 4
optim: AdamW
lr: 3e-05
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
net: resnet18
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10099
dist_backend: nccl
gpu: None
uratio: 1
include_lb_to_ulb: False
mixup_alpha: 0.3
loss_weight_mixup: 0.03
target_classes: [0, 1, 8, 9]
neg_classes: None
num_pos_data: 500
num_ulb_data: None
