algorithm: count_loss_proportion
save_dir: ./saved_models/proportion/classic_cv/count_loss_proportion
save_name: count_loss_proportion_imagenet100_target100_bags20000_mean3_std1_42
resume: True
load_path: ./saved_models/proportion/classic_cv/count_loss_proportion/count_loss_proportion_imagenet100_target100_bags20000_mean3_std1_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_eval_iter: None
num_log_iter: 10
batch_size: 8
eval_batch_size: 128
crop_ratio: 0.875
img_size: 224
data_dir: /mnt/data/dataset
dataset: imagenet100
num_classes: 100
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: True
clip: 5.0
net: resnet34
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10082
dist_backend: nccl
gpu: None
target_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
mean_bag_len: 3
std_bag_len: 1
num_bags_train: 20000
