algorithm: imp_proportion
save_dir: ./saved_models/proportion/classic_cv/imp_proportion
save_name: imp_proportion_cifar10_target10_bags10000_mean5_std1_42
resume: True
load_path: ./saved_models/proportion/classic_cv/imp_proportion/imp_proportion_cifar10_target10_bags10000_mean5_std1_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_eval_iter: None
num_log_iter: 25
batch_size: 4
eval_batch_size: 128
crop_ratio: 0.875
img_size: 32
data_dir: ./data
dataset: cifar10
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
net: wrn_28_2
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10042
dist_backend: nccl
gpu: 0
target_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
mean_bag_len: 5
std_bag_len: 1
num_bags_train: 10000
