algorithm: llp_vat_proportion
save_dir: ./saved_models/proportion/classic_cv/llp_vat_proportion
save_name: llp_vat_proportion_mnist_target10_bags500_mean20_std10_42
resume: True
load_path: ./saved_models/proportion/classic_cv/llp_vat_proportion/llp_vat_proportion_mnist_target10_bags500_mean20_std10_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 30
num_eval_iter: None
num_log_iter: 25
batch_size: 2
eval_batch_size: 128
crop_ratio: 1.0
img_size: 28
data_dir: ./data
dataset: mnist
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.0005
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
net: lenet5
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10019
dist_backend: nccl
gpu: 0
vat_xi: 1e-06
vat_eps: 6.0
vat_ip: 1
prop_metric: ce
loss_weight_cons: 1.0
target_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
mean_bag_len: 20
std_bag_len: 10
num_bags_train: 500
