algorithm: llp_vat_proportion
save_dir: ./saved_models/proportion/classic_cv/llp_vat_proportion
save_name: llp_vat_proportion_stl10_target10_bags1000_mean10_std2_42
resume: True
load_path: ./saved_models/proportion/classic_cv/llp_vat_proportion/llp_vat_proportion_stl10_target10_bags1000_mean10_std2_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_eval_iter: None
num_log_iter: 25
batch_size: 4
eval_batch_size: 128
crop_ratio: 0.875
img_size: 96
data_dir: ./data
dataset: stl10
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
net: resnet18
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10079
dist_backend: nccl
gpu: 0
vat_xi: 1e-06
vat_eps: 6.0
vat_ip: 1
prop_metric: ce
loss_weight_cons: 1.0
target_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
mean_bag_len: 10
std_bag_len: 2
num_bags_train: 1000
