algorithm: uum_proportion
save_dir: ./saved_models/proportion/classic_cv/uum_proportion
save_name: uum_proportion_stl10_target1_bags1000_mean5_std1_42
resume: True
load_path: ./saved_models/proportion/classic_cv/uum_proportion/uum_proportion_stl10_target1_bags1000_mean5_std1_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_eval_iter: None
num_log_iter: 25
batch_size: 4
eval_batch_size: 128
crop_ratio: 0.875
img_size: 96
data_dir: ./data
dataset: stl10
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip: 0.0
net: resnet18
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10074
dist_backend: nccl
gpu: 0
target_classes: [3]
mean_bag_len: 5
std_bag_len: 1
num_bags_train: 1000
