algorithm: imp_semisup
save_dir: ./saved_models/semisup/classic_cv
save_name: imp_semisup_cifar100_400_42
resume: True
load_path: ./saved_models/semisup/classic_cv/imp_semisup_cifar100_400_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 256
num_train_iter: 262144
num_eval_iter: 2560
num_log_iter: 256
num_labels: 400
batch_size: 64
eval_batch_size: 256
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
net: wrn_28_8
net_from_name: False
data_dir: ./data
dataset: cifar100
num_classes: 100
num_workers: 2
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10001
dist_backend: nccl
gpu: None
uratio: 7
include_lb_to_ulb: True
average_entropy_loss: True
