algorithm: imp_sim_conf
save_dir: ./saved_models/sim_conf/classic_cv/imp_sim_conf
save_name: imp_sim_conf_cifar10_target4_neg6_pair25000_prior0.4_openclip_ViT-B-16_openai_42
resume: True
load_path: ./saved_models/sim_conf/classic_cv/imp_sim_conf/imp_sim_conf_cifar10_target4_neg6_pair25000_prior0.4_openclip_ViT-B-16_openai_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_train_iter: None
num_eval_iter: None
num_log_iter: 50
batch_size: 64
eval_batch_size: 128
epoch: 50
crop_ratio: 0.875
img_size: 32
data_dir: ./data
dataset: cifar10
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
net: wrn_28_2
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10041
dist_backend: nccl
gpu: 0
strong_aug: False
target_classes: [0, 1, 8, 9]
neg_classes: None
num_pair_data: 25000
class_prior: 0.4
conf_model_name: openclip_ViT-B-16_openai
