algorithm: imp_partial_noisy_ulb
save_dir: ./saved_models/partial_noisy_ulb/classic_cv
save_name: imp_partial_noisy_ulb_cifar10_lb50000_n0.2_p0.3_42
resume: True
load_path: ./saved_models/partial_noisy_ulb/classic_cv/imp_partial_noisy_ulb_cifar10_lb50000_n0.2_p0.3_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 150
num_train_iter: 307200
num_eval_iter: 1024
num_log_iter: 256
num_labels: 50000
batch_size: 64
eval_batch_size: 256
ema_m: 0.999
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.02
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
net: resnet18
net_from_name: False
data_dir: ./data
dataset: cifar10
num_classes: 10
num_workers: 4
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10050
dist_backend: nccl
gpu: None
uratio: 3
include_lb_to_ulb: True
average_entropy_loss: True
noise_ratio: 0.2
partial_ratio: 0.3
noise_matrix_scale: 1.0
