algorithm: imp_partial_label
save_dir: ./saved_models/partial_label/rcr_cv
save_name: imp_partial_label_cifar10_0.1_42
resume: True
load_path: ./saved_models/partial_label/rcr_cv/imp_partial_label_cifar10_0.1_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 200
num_eval_iter: None
num_log_iter: 50
batch_size: 64
eval_batch_size: 256
partial_ratio: 0.1
ema_m: 0.0
crop_ratio: 0.875
img_size: 32
optim: SGD
lr: 0.1
momentum: 0.9
weight_decay: 0.0001
layer_decay: 1.0
amp: False
clip_grad: 1.0
net: wrn_34_10
net_from_name: False
data_dir: ./data
dataset: cifar10
num_classes: 10
num_workers: 4
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10013
dist_backend: nccl
gpu: None
strong_aug: True
average_entropy_loss: True
