algorithm: count_loss_multi_ins
save_dir: ./saved_models/multi_ins/classic_cv/count_loss_multi_ins
save_name: count_loss_multi_ins_stl10_target10_bags2000_mean5_std1_42
resume: True
load_path: ./saved_models/multi_ins/classic_cv/count_loss_multi_ins/count_loss_multi_ins_stl10_target10_bags2000_mean5_std1_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_eval_iter: None
num_log_iter: 25
batch_size: 2
eval_batch_size: 128
data_dir: ./data
crop_ratio: 0.875
img_size: 96
dataset: stl10
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
net: resnet18
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10063
dist_backend: nccl
gpu: None
target_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
mean_bag_len: 5
std_bag_len: 1
num_bags_train: 2000
balanced_bags: False
