algorithm: imp_multi_ins
save_dir: ./saved_models/multi_ins/classic_cv/imp_multi_ins
save_name: imp_multi_ins_cifar10_target1_bags2500_mean10_std2_42
resume: True
load_path: ./saved_models/multi_ins/classic_cv/imp_multi_ins/imp_multi_ins_cifar10_target1_bags2500_mean10_std2_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_eval_iter: None
num_log_iter: 25
batch_size: 4
eval_batch_size: 128
data_dir: ./data
crop_ratio: 0.875
img_size: 32
dataset: cifar10
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
net: wrn_28_2
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10050
dist_backend: nccl
gpu: None
strong_aug: False
target_classes: [3]
mean_bag_len: 10
std_bag_len: 2
num_bags_train: 2500
balanced_bags: True
