algorithm: imp_multi_ins
save_dir: ./saved_models/multi_ins/classic_cv/imp_multi_ins
save_name: imp_multi_ins_fmnist_target1_bags500_mean10_std2_42
resume: True
load_path: ./saved_models/multi_ins/classic_cv/imp_multi_ins/imp_multi_ins_fmnist_target1_bags500_mean10_std2_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 50
num_eval_iter: None
num_log_iter: 25
batch_size: 2
eval_batch_size: 128
data_dir: ./data
crop_ratio: 1.0
img_size: 28
dataset: fmnist
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.0005
momentum: 0.9
weight_decay: 1e-05
layer_decay: 1.0
amp: False
clip: 0.0
net: lenet5
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10032
dist_backend: nccl
gpu: None
strong_aug: False
target_classes: [9]
mean_bag_len: 10
std_bag_len: 2
num_bags_train: 500
balanced_bags: True
