algorithm: pcomp_teacher_pair_comp
save_dir: /mnt/imprecise_label_learning_weak_supervision_haoc/projects/connectionise_imprecise_label_learning/240206_saved_models/pair_comp/classic_cv
save_name: pcomp_teacher_pair_comp_cifar100_target40_neg60_pair20000_prior0.2_42
resume: True
load_path: /mnt/imprecise_label_learning_weak_supervision_haoc/projects/connectionise_imprecise_label_learning/240206_saved_models/pair_comp/classic_cv/pcomp_teacher_pair_comp_cifar100_target40_neg60_pair20000_prior0.2_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_train_iter: None
num_eval_iter: None
num_log_iter: 50
batch_size: 64
eval_batch_size: 128
epoch: 100
crop_ratio: 0.875
img_size: 32
data_dir: /mnt/data/dataset/imprecise_datasets
dataset: cifar100
num_classes: 100
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
net: resnet18
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10067
dist_backend: nccl
gpu: 0
target_classes: [4, 30, 55, 72, 95, 1, 32, 67, 73, 91, 3, 42, 43, 88, 97, 15, 19, 21, 31, 38, 34, 63, 64, 66, 75, 26, 45, 77, 79, 99, 27, 29, 44, 78, 93, 36, 50, 65, 74, 80]
neg_classes: None
num_pair_data: 20000
class_prior: 0.2
