algorithm: rank_pruning_pair_comp
save_dir: /mnt/imprecise_label_learning_weak_supervision_haoc/projects/connectionise_imprecise_label_learning/240206_saved_models/pair_comp/classic_cv
save_name: rank_pruning_pair_comp_cifar10_target4_neg6_pair20000_prior0.8_42
resume: True
load_path: /mnt/imprecise_label_learning_weak_supervision_haoc/projects/connectionise_imprecise_label_learning/240206_saved_models/pair_comp/classic_cv/rank_pruning_pair_comp_cifar10_target4_neg6_pair20000_prior0.8_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
num_train_iter: None
num_eval_iter: None
num_log_iter: 50
batch_size: 64
eval_batch_size: 128
epoch: 50
crop_ratio: 0.875
img_size: 32
data_dir: /mnt/data/dataset/imprecise_datasets
dataset: cifar10
num_classes: 10
num_workers: 4
optim: AdamW
lr: 0.001
momentum: 0.9
weight_decay: 0.001
layer_decay: 1.0
amp: False
clip: 0.0
net: wrn_28_2
net_from_name: False
ema_m: 0.0
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10054
dist_backend: nccl
gpu: 0
target_classes: [0, 1, 8, 9]
neg_classes: None
num_pair_data: 20000
class_prior: 0.8
