algorithm: imp_noisy_label
save_dir: ./saved_models/noisy_label/classic_cv
save_name: imp_noisy_label_webvision_ins_1.0_42
resume: True
load_path: ./saved_models/noisy_label/classic_cv/imp_noisy_label_webvision_ins_1.0_42/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_eval_iter: None
num_log_iter: 50
batch_size: 32
eval_batch_size: 256
noise_ratio: 1.0
noise_type: ins
ema_m: 0.0
crop_ratio: 0.95
img_size: 299
optim: SGD
lr: 0.02
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
net: inception_resnet_v2
net_from_name: False
data_dir: ./data
dataset: webvision
num_classes: 50
num_workers: 4
seed: 42
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10007
dist_backend: nccl
gpu: None
strong_aug: True
average_entropy_loss: True
noise_matrix_scale: 2.5
